# Generated by Django 3.2.18 on 2023-08-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='routemodel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=123)),
                ('age1', models.IntegerField()),
                ('Gender1', models.CharField(max_length=123)),
            ],
            options={
                'db_table': 'route_table1',
            },
        ),
    ]
